name: whatsapp_bot_platform_interface
description: Whatsapp bot platform interface
version: 0.0.1
homepage: https://github.com/rohitsangwan01/whatsapp_bot_flutter
repository: https://github.com/rohitsangwan01/whatsapp_bot_flutter
issue_tracker: https://github.com/rohitsangwan01/whatsapp_bot_flutter/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  zxing2: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


