name: example_dart
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  whatsapp_bot_flutter:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
