name: example_dart
description: start a puppeteer server
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  puppeteer: ^2.17.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
